### ISSUE TITLE
Cannot load layout from file via layout=layout

### ISSUE THREAD

**Issue by chris-aeviator** [Renumics/spotlight#133]
**Describe the bug**
When saving a layout from the UI and trying to load it via 

    df_show = df.drop(columns=['embedding', 'probabilities'])
    layout_url = "http://my-layout.json"
    response = requests.get(layout_url)
    layout = spotlight.layout.nodes.Layout(**json.loads(response.text))
    spotlight.show(df_show, dtype={"image": spotlight.Image, "embedding_reduced": spotlight.Embedding}, layout=layout)

**To Reproduce**

**Expected behavior**
Layout is loaded.

**Screenshots**
    ```
    {'orientation': 'vertical', 'children': [{'kind': 'split', 'weight': 60, 'orientation': 'horizontal', 'children': [{'kind': 'tab', 'weight': 60, 'children': [{'kind': 'widget', 'name': 'Table', 'type': 'table', 'config': {'tableView': 'full', 'visibleColumns': None, 'sorting': None, 'orderByRelevance': False}}]}, {'kind': 'tab', 'weight': 40, 'children': [{'kind': 'widget', 'name': 'Similarity Map', 'type': 'similaritymap', 'config': {'placeBy': ['score'], 'reductionMethod': None, 'colorBy': 'run_id', 'sizeBy': None, 'filter': False, 'umapNNeighbors': 20, 'umapMetric': None, 'umapMinDist': 0.15, 'pcaNormalization': None, 'umapMenuLocalGlobalBalance': None, 'umapMenuIsAdvanced': False}}, {'kind': 'widget', 'name': 'Scatter Plot', 'type': 'scatterplot', 'config': {'xAxisColumn': 'score', 'yAxisColumn': 'beam', 'colorBy': 'run_id', 'sizeBy': None, 'filter': False}}, {'kind': 'widget', 'name': 'Histogram', 'type': 'histogram', 'config': {'columnKey': 'score', 'stackByColumnKey': 'run_id', 'filter': False}}]}]}, {'kind': 'tab', 'weight': 40, 'children': [{'kind': 'widget', 'name': 'Inspector', 'type': 'inspector', 'config': {'views': [{'view': 'MarkdownLens', 'columns': ['text'], 'name': 'view', 'key': '6e48e9eb-926b-4a35-9249-0e02d23d6a2c'}, {'view': 'MarkdownLens', 'columns': ['scored_text'], 'name': 'view', 'key': 'ad9eb104-a8d6-47ad-9b00-746135d60551'}], 'visibleColumns': 1}}]}]}
        Traceback (most recent call last):
          File "/myfolder/myfile.py", line 18, in <module>
            layout = spotlight.layout.nodes.Layout(**json.loads(response.text))
          File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
            return _default_decoder.decode(s)
          File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
            obj, end = self.raw_decode(s, idx=_w(s, 0).end())
          File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
            raise JSONDecodeError("Expecting value", s, err.value) from None
        json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Desktop (please complete the following information):**

-   OS: arch linux
-   Browser: Firefox
-   Browser Version [e.g. 22]
-   Spotlight Version  renumics-spotlight 1.3.0rc3 ,  renumics-spotlight 1.2.0 

**Additional context**

**Comment by druzsan** [comment]
You don't have to instantiate Spotlight layout yourself, use one of the following:
```python
from renumics import spotlight
# Local file
spotlight.show(df, layout="path/to/layout.json")
# URL
spotlight.show(df, layout="https://path.to/layout.json")
```
---
Still, your code is valid so I assume that the content of your JSON file isn't a valid JSON. At least this
> `{'orientation': 'vertical', 'children': [{'kind': 'split'...`

is not a valid JSON, it is a valid Spotlight layout *object* which can be directly fed into the `spotlight.layout.nodes.Layout`.
The proper JSON content should look approximately like
<details>
    <summary>this (unfortunately, I cannot upload a JSON file here)</summary>

```json
{
    "orientation": "vertical",
    "children": [
        {
            "kind": "split",
            "weight": 60,
            "orientation": "horizontal",
            "children": [
                {
                    "kind": "tab",
                    "weight": 60,
                    "children": [
                        {
                            "kind": "widget",
                            "name": "Table",
                            "type": "table",
                            "config": {
                                "tableView": "full",
                                "visibleColumns": null,
                                "sorting": null,
                                "orderByRelevance": false
                            }
                        }
                    ]
                },
                {
                    "kind": "tab",
                    "weight": 40,
                    "children": [
                        {
                            "kind": "widget",
                            "name": "Similarity Map",
                            "type": "similaritymap",
                            "config": {
                                "placeBy": ["score"],
                                "reductionMethod": null,
                                "colorBy": "run_id",
                                "sizeBy": null,
                                "filter": false,
                                "umapNNeighbors": 20,
                                "umapMetric": null,
                                "umapMinDist": 0.15,
                                "pcaNormalization": null,
                                "umapMenuLocalGlobalBalance": null,
                                "umapMenuIsAdvanced": false
                            }
                        },
                        {
                            "kind": "widget",
                            "name": "Scatter Plot",
                            "type": "scatterplot",
                            "config": {
                                "xAxisColumn": "score",
                                "yAxisColumn": "beam",
                                "colorBy": "run_id",
                                "sizeBy": null,
                                "filter": false
                            }
                        },
                        {
                            "kind": "widget",
                            "name": "Histogram",
                            "type": "histogram",
                            "config": {
                                "columnKey": "score",
                                "stackByColumnKey": "run_id",
                                "filter": false
                            }
                        }
                    ]
                }
            ]
        },
        {
            "kind": "tab",
            "weight": 40,
            "children": [
                {
                    "kind": "widget",
                    "name": "Inspector",
                    "type": "inspector",
                    "config": {
                        "views": [
                            {
                                "view": "MarkdownLens",
                                "columns": ["text"],
                                "name": "view",
                                "key": "6e48e9eb-926b-4a35-9249-0e02d23d6a2c"
                            },
                            {
                                "view": "MarkdownLens",
                                "columns": ["scored_text"],
                                "name": "view",
                                "key": "ad9eb104-a8d6-47ad-9b00-746135d60551"
                            }
                        ],
                        "visibleColumns": 1
                    }
                }
            ]
        }
    ]
}
```

</details>

With this content saved into a file or an URL one can instantiate a Spotlight layout:
```python
import json
import requests
from renumics.spotlight.layout.nodes import Layout
# Local file
with open("path/to/layout.json", "r") as file:
    layout_obj = json.loads(file.read())
layout = Layout(**layout_obj)
# URL
response = requests.get("https://path.to/layout.json")
layout_obj = json.loads(response.text)
layout = Layout(**layout_obj)
```
and then start Spotlight `spotlight.show(df, layout=layout)`.

**Comment by druzsan** [comment]
@chris-aeviator if something above doesn't work for you, feel free to reopen the issue.
