### ISSUE TITLE
Spotlight cannot be started under Python 3.10.9 (Miniconda)

### ISSUE THREAD

**Issue by dani2112** [Renumics/spotlight#137]
**Describe the bug**
When running Spotlight 1.3.0rc3 under Ubuntu/Miniconda/Python 3.10.9 it immediately fails with this message:

```
Traceback (most recent call last):
  File "/home/**/code/**-test/.venv/bin/spotlight", line 5, in <module>
    from renumics.spotlight.cli import main
  File "/home/**/code/**-test/.venv/lib/python3.10/site-packages/renumics/spotlight/__init__.py", line 18, in <module>
    from .viewer import Viewer, close, viewers, show
  File "/home/**/code/**-test/.venv/lib/python3.10/site-packages/renumics/spotlight/viewer.py", line 63, in <module>
    from renumics.spotlight.layout import _LayoutLike, parse
  File "/home/**/code/**-test/.venv/lib/python3.10/site-packages/renumics/spotlight/layout/__init__.py", line 26, in <module>
    from .nodes import (
  File "/home/**/code/**-test/.venv/lib/python3.10/site-packages/renumics/spotlight/layout/nodes.py", line 15, in <module>
    from .widgets import Widget
  File "/home/**/code/**-test/.venv/lib/python3.10/site-packages/renumics/spotlight/layout/widgets.py", line 11, in <module>
    class WidgetConfig(BaseModel, allow_population_by_field_name=True):
  File "/home/**/code/**-test/.venv/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 124, in __new__
    cls: type[BaseModel] = super().__new__(mcs, cls_name, bases, namespace, **kwargs)  # type: ignore
  File "/home/**/miniconda3/lib/python3.10/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: WidgetConfig.__init_subclass__() takes no keyword arguments

```

**To Reproduce**

1. Setup new virtualenv with Python 3.10.9 (miniconda python version)
2. Activate venv and run pip install renumics-spotlight==1.3.0rc3
3. Run spotlight

**Expected behavior**
It should work flawlessly.

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04, Miniconda, Python 3.10.9
-   Spotlight Version 1.3.0rc3

**Comment by dani2112** [comment]
Just found out that downgrading pydantic to 1.10.11 resolves the issue.

The installed version in my env was 2.0.2 before.

However, pydantic is not pinned when installing spotlight, so this is still an issue as incompatible version is installed.

**Comment by neindochoh** [comment]
Pydantic is already pinned to <2.0.0 on **main**. A version of Spotlight containing this fix will be released soon.

For now, you can work around this issue by manually installing an earlier version of pydantic:
```bash
pip install pydantic==1.10.11
```
